name: logistream
version: 1.0.0
config-version: 2
profile: logistream
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: target
clean-targets: [target, dbt_packages]

models:
  logistream:
    staging:
      +schema: silver
      +materialized: view
    marts:
      +schema: gold
      +materialized: table
      demand:
        +tags: ["demand"]
      routes:
        +tags: ["routes"]
